### ISSUE TITLE
Resolve issues with recipes.json

### ISSUE THREAD

**Issue by gmihir** [cse110-fa21-group34/rocketrecipes#101]
There are some issues with recipes.json (fields are null, duplicate recipes, etc.)

For reference:
- recipes with null fields: Chocolate Mousse in Chocolate Shell
- recipes that are duplicated: Fast tiramisu

**Comment by srjsml** [comment]
Another issue found:
- Remove trailing values by converting decimal values into fractions: Easy Cheesy Pizza Casserole, milk ingredient at 0.6666666666666666 cup milk

**Comment by PatrickBrown1** [comment]
Greek-Style Baked Fish: Fresh, Simple, and Delicious,
Fast tiramisu,
Panna cotta with raspberry and orange sauce,
have duplicates
