### ISSUE TITLE
Redesign application UI and create prototype

### ISSUE THREAD

**Issue by gmihir** [cse110-fa21-group34/rocketrecipes#109]
The UI/UX for the application needs to be redesigned to be more user-friendly and aesthetically appealing. Additionally, users should be able to use the application on different sized devices.

Specific feedback:
- Redesign button placement, especially on the individual recipe page
- Add a back button on the individual recipe page
- Add more color, better fonts, etc.

- [ ] A prototype has been designed in Figma for desktop UI
- [ ] A prototype has been designed in Figma for mobile UI

**Comment by gmihir** [comment]
Additional information: recipe summary should be visible on the recipe page. PR #117 has stripped out the HTML from the summary field for easier development.

**Comment by PatrickBrown1** [comment]
done in figma
