### ISSUE TITLE
Implement share button(s)

### ISSUE THREAD

**Issue by gmihir** [cse110-fa21-group34/rocketrecipes#111]
Another one of our domain specific features is a share button for recipes. This share button should print the screen (https://developer.mozilla.org/en-US/docs/Web/API/Window/print). 

Additionally, there should be a share button for at least 1 social network (Facebook, Twitter, Pinterest, etc.) that should be available for all recipes that are scraped (i.e. they are not user-created). This is because we are relying on localStorage. Possible resources to look at: https://developer.twitter.com/en/docs/twitter-for-websites/tweet-button/overview (prepopulate with recipe title and url or something)

- [x] The primary share button is visible for all recipes (on the recipe page) and calls the print web API
- [x] There is at least 1 social network share button implemented which shares the url of the recipe
- [x] The social network button is only visible on common (scaped) recipes.

**Comment by PatrickBrown1** [comment]
Need to make sure the share button is only visible when the recipe is a common recipe, not a user specific recipe

**Comment by PatrickBrown1** [comment]
#186
