### ISSUE TITLE
Read search query on search page if it exists

### ISSUE THREAD

**Issue by gmihir** [cse110-fa21-group34/rocketrecipes#114]
The current search page always starts on a blank screen. However, if the user goes back from a recipe they clicked, their search is gone. The application should remember the search.

- [ ] The init() function for search page checks if the searchQuery and tags query parameters exist. if they do, it parses them and executes the search they correspond to

**Comment by PatrickBrown1** [comment]
I believe the page does remember the search by showing the cards of the previous search. However, the search bar and filters get emptied whenever the search is actually executed. When the page is loaded, fill the search bar and filters based on what exists in the query params
