### ISSUE TITLE
Null entry detection on 'Create Recipe' page

### ISSUE THREAD

**Issue by srjsml** [cse110-fa21-group34/rocketrecipes#89]
Should prevent user from entering null fields on Create Recipe page. (not priority until after Monday, Nov 22 discussion)

**Comment by gmihir** [comment]
To add to this, the create recipe page should not allow a user to add a new ingredient/step until the previous one is filled

**Comment by gmihir** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Window/alert
